#!/system/bin/sh

config=/res/synapse/config.json
action=/res/synapse/actions/

if [ ! -f $config ]
then
    source /res/synapse/config.json.generate > $config
fi

case $1 in
config)
  cat $config
  ;;
configpath)
  echo $config
  ;;
actionpath)
  echo $action
  ;;
esac
