#
# Makefile for the sensor hub.
#

#Disable Strict Aliasing Optimizations
CFLAGS_KERNEL += -fno-strict-aliasing

obj-$(CONFIG_SENSORS_SSP_BBD)	+= brcm/
obj-$(CONFIG_SENSORS_SSP_STM)	+= stm/
obj-$(CONFIG_SENSORS_SSP_ATMEL)	+= atmel/
